User can create a todo.
ryanchangyeolshin/continuous-delivery pull request #8
Opened 2017-11-02 20:29 UTC by ryanchangyeolshin

![image](https://user-images.githubusercontent.com/16450416/32348657-b16af870-bfd1-11e7-9fe1-b6a0367c617d.png)

![image](https://user-images.githubusercontent.com/16450416/32348671-c097251c-bfd1-11e7-8705-27f1e7d5dbcd.png)

2017-11-02 20:58 UTC, thebearingedge commented
Did you mean to send a `.txt` to `occs-ten`?

2017-11-02 21:03 UTC, ryanchangyeolshin commented
Not yet. Wanted to double check my work. The tests seem to run fine, but can't be too sure.

2017-11-02 22:35 UTC, thebearingedge requested changes

2017-11-02 22:35 UTC, thebearingedge commented on client/todo-form.js
> +      _id: uuid(),
Don't create the `uuid` here, let your server do it.

2017-11-02 22:35 UTC, thebearingedge commented on client/todo-form.js
> +    axios.post('http://localhost:3000/api/todos', data)
Just hit `'/api/todos'`. You don't want to hard-code your `origin`.

2017-11-02 22:35 UTC, thebearingedge commented on package.json
> +    "path": "^0.12.7",
`path` is built into Node, you don't need to `npm install` it.

2017-11-02 22:35 UTC, thebearingedge commented on server/create-app.js
> +      const _todos = await findTodos(todos)
Doesn't `findTodos` have a closure over the collection?

2017-11-02 22:35 UTC, thebearingedge commented on sync.js
> +  // server: 'server/public',
You can delete this comment.

2017-11-02 22:35 UTC, thebearingedge commented on test/index.test.js
> +      const repo = await axios.get('http://localhost:3000/api')
Use your `process.env.PORT` instead of hard-coding it.

2017-11-02 22:35 UTC, thebearingedge commented on server/todos-gateway.js
> +      return todo
Just return the inserted `todo` instead of the MongoDB `result` object.

2017-11-02 22:35 UTC, thebearingedge commented on test/todos-gateway.test.js
> +      expect(ops[0]).to.deep.equal(data)
Notice how your test has to reach into the `ops`. Just make your function return what your really want.

2017-11-03 17:17 UTC, thebearingedge approved these changes

2017-11-03 17:17 UTC, merged